version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "technical_task"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: "redis:alpine"

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  celery:
    build: .
    command: celery -A api_vantage worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A api_vantage beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  db: